[package]
name = "md_to_pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "^0.4"
env_logger = "^0.11"
debugging = { git = "https://github.com/a-givertzman/rust-debuging.git", tag = "0.0.1" }
#
# Collections
indexmap = "^2.7"
#
# Regex
regex = "^1.11"
#
# Md
markdown = "1.0.0-alpha.21"
comrak = "^0.32"
